const translations = {
  en: {
    home: "Home",
    gallery: "Gallery",
    about: "About Us",
    explore_trips: "Explore Our Trip Types",
    hero_desc: "Unforgettable experiences with full services included.",
    trip1_title: "Satayah - Swim with Dolphins",
    trip1_desc: "Enjoy swimming with dolphins in the Red Sea in a magical experience.",
    trip2_title: "Marsa Mubarak - Turtles & Dugong",
    trip2_desc: "A sea trip to see turtles, dugong, and stunning coral reefs.",
    trip3_title: "Hamata Islands - 3 Snorkeling Spots",
    trip3_desc: "Snorkel in 3 different spots and visit the magical Siyal Island.",
    inclusive_meal: "Includes lunch + open buffet",
    drinks: "Drinks throughout the trip",
    transport: "Transport to and from the hotel",
    about_title: "About Sea Moon Tours",
    about_desc: "Sea Moon Tours is a professional marine trips company based in Marsa Alam, Red Sea Governorate, Egypt. We offer unforgettable adventures in the Red Sea including dolphin swims, snorkeling trips, and coral reef tours.",
    contact_title: "Contact Us",
    trip_title: "Satayah - Swim with Dolphins",
    trip_description: "An unforgettable experience swimming with dolphins in the clear waters of Satayah! Join us for an amazing marine adventure including a boat tour and time with dolphins, with professional guides and full safety equipment.",
    price: "Price",
    duration: "Duration",
    trip_duration: "Full day",
    location: "Location",
    trip_location: "Satayah Reef, Marsa Alam",
    book_now: "Show Details",
    trip2_full_title: "Marsa Mubarak - Swim with Dugong & Turtles",
    trip2_description: "A special sea trip in Marsa Mubarak! Enjoy snorkeling in two beautiful spots to see dugongs and sea turtles in turquoise waters. Includes:",
    trip2_point1: "🏖️ Two snorkeling and swimming spots",
    trip2_point2: "🐢 See dugongs and turtles in their natural habitat",
    trip2_point3: "🍽️ Delicious lunch onboard",
    trip2_point4: "🥤 Hot and cold drinks all day",
    trip2_point5: "🚐 Transfers to and from hotel included",
    trip2_location: "Marsa Mubarak, Marsa Alam",
    trip2_duration: "Full Day",
    trip3_title: "Hamata Islands - Snorkeling at 3 Sites & Siyal Island Visit",
    trip3_description: "Enjoy a full-day adventure snorkeling at 3 beautiful reef spots and visiting Siyal Island.",
    trip3_point1: "Snorkeling at 3 different stunning coral reef sites",
    trip3_point2: "Visit to the untouched Siyal Island",
    trip3_point3: "Delicious open buffet lunch on board",
    trip3_point4: "Hot and cold drinks available all day",
    trip3_point5: "Hotel pick-up and drop-off included in price",
    trip3_duration: "Full day",
    trip3_location: "Hamata",
    trip4_full_title: "Orange Bay - Snorkeling & Water Activities",
    trip4_description: "A fun day trip to Orange Bay, Hurghada! Enjoy snorkeling at 2 spots and 2 hours of water activities on the island. Includes:",
    trip4_point1: "Two snorkeling stops",
    trip4_point2: "Two hours of water activities on the island",
    trip4_duration: "Full Day",
    trip4_location: "Orange Bay, Hurghada",
    trip5_full_title: "Hula Hula Island - Snorkeling & Water Activities",
    trip5_description: "A fun day trip to Hula Hula Island, Hurghada! Enjoy snorkeling at 2 spots and 2 hours of water activities on the island. Includes:",
    trip5_point1: "Two snorkeling stops",
    trip5_point2: "Two hours of water activities on the island",
    trip5_duration: "Full Day",
    trip5_location: "Hula Hula Island, Hurghada",
    trip6_full_title: "Paradise Island - Snorkeling & Water Activities",
    trip6_description: "A fun day trip to Paradise Island, Hurghada! Enjoy snorkeling at 2 spots, 2 hours on the island, and water activities. Includes:",
    trip6_point1: "Two snorkeling stops",
    trip6_point2: "Two hours on the island",
    trip6_point3: "Water activities stop",
    trip6_duration: "Full Day",
    trip6_location: "Paradise Island, Hurghada",
    trip7_full_title: "Mountain & Desert Safari",
    trip7_description: "An exciting safari in Marsa Alam's mountains and desert with buggy rides, Bedouin camp, horse and camel riding. Includes:",
    trip7_point1: "Buggy ride through the desert",
    trip7_point2: "Visit to a Bedouin camp",
    trip7_point3: "Horse and camel riding",
    trip7_duration: "Full Day",
    trip7_location: "Marsa Alam Desert",
  },
  ar: {
    home: "الرئيسية",
    gallery: "المعرض",
    about: "معلومات عنا",
    explore_trips: "اكتشف أنواع الرحلات",
    hero_desc: "تجارب لا تُنسى مع خدمات شاملة.",
    trip1_title: "سطايح - السباحة مع الدلافين",
    trip1_desc: "استمتع بالسباحة مع الدلافين في البحر الأحمر في تجربة ساحرة.",
    trip2_title: "مرسى مبارك - السلاحف وعرائس البحر",
    trip2_desc: "رحلة بحرية لرؤية السلاحف والعرائس البحرية والشعاب المرجانية الرائعة.",
    trip3_title: "جزر حماطة - 3 أماكن للغطس",
    trip3_desc: "اغطس في 3 أماكن مختلفة وقم بزيارة جزيرة سيال الساحرة.",
    inclusive_meal: "يشمل الغداء وبوفيه مفتوح",
    drinks: "مشروبات طوال الرحلة",
    transport: "نقل من وإلى الفندق",
    about_title: "عن شركة سي مون تورز",
    about_desc: "سي مون تورز هي شركة متخصصة في تنظيم الرحلات البحرية في مرسى علم، محافظة البحر الأحمر. نقدم مغامرات لا تُنسى في البحر الأحمر، مثل السباحة مع الدلافين والسنوركل ورحلات الشعاب المرجانية.",
    contact_title: "تواصل معنا",
    trip_title: "سطايح - عوم مع الدولفين",
    trip_description: "تجربة لا تُنسى للسباحة مع الدلافين في مياه سطايح الصافية! انضم إلينا في مغامرة بحرية مدهشة تشمل جولة بالقارب ووقت ممتع مع الدلافين، مع مرشدين محترفين وتجهيزات أمان كاملة.",
    price: "السعر",
    duration: "المدة",
    trip_duration: "يوم كامل",
    location: "الموقع",
    trip_location: "شط سطايح، مرسى علم",
    book_now: "عرض التفاصيل",
    trip2_full_title: "مرسى مبارك - عوم مع الدوجونج والسلاحف",
    trip2_description: "رحلة بحرية مميزة في مرسى مبارك! استمتع بالغوص في موقعين رائعين لمشاهدة الدوجونج والسلاحف البحرية وسط المياه الفيروزية، تشمل:",
    trip2_point1: "🏖️ محطتين للعوم والغطس (Snorkeling)",
    trip2_point2: "🐢 مشاهدة الدوجونج والسلاحف في بيئتها الطبيعية",
    trip2_point3: "🍽️ غداء لذيذ على ظهر المركب",
    trip2_point4: "🥤 مشروبات ساخنة وباردة طوال اليوم",
    trip2_point5: "🚐 الانتقالات من وإلى الفندق مشمولة في السعر",
    trip2_location: "مرسى مبارك، مرسى علم",
    trip2_duration: "يوم كامل",
    trip3_title: "جزر حماطة - رحلة الغطس في ٣ مواقع وزيارة جزيرة سيال",
    trip3_description: "استمتع برحلة مغامرة ليوم كامل تشمل الغطس في ٣ مواقع شعاب مرجانية وزيارة جزيرة سيال.",
    trip3_point1: "الغطس في ٣ مواقع مختلفة رائعة",
    trip3_point2: "زيارة جزيرة سيال البكر",
    trip3_point3: "غداء بوفيه مفتوح شهي على المركب",
    trip3_point4: "مشروبات ساخنة وباردة طوال اليوم",
    trip3_point5: "الانتقالات من وإلى الفندق مشمولة في السعر",
    trip3_duration: "يوم كامل",
    trip3_location: "حماطة",
    trip4_full_title: "جزيرة أورانج باي - الغطس والألعاب المائية",
    trip4_description: "رحلة يوم ممتع إلى جزيرة أورانج باي، الغردقة! استمتع بالغطس في ٢ موقع و٢ ساعات من الألعاب المائية على الجزيرة، وتشمل:",
    trip4_point1: "٢ وقفة غطس",
    trip4_point2: "٢ ساعات من الألعاب المائية على الجزيرة",
    trip4_duration: "يوم كامل",
    trip4_location: "جزيرة أورانج باي، الغردقة",
    trip5_full_title: "جزيرة هولا هولا - الغطس والألعاب المائية",
    trip5_description: "رحلة يوم ممتع إلى جزيرة هولا هولا، الغردقة! استمتع بالغطس في ٢ موقع و٢ ساعات من الألعاب المائية على الجزيرة، وتشمل:",
    trip5_point1: "٢ وقفة غطس",
    trip5_point2: "٢ ساعات من الألعاب المائية على الجزيرة",
    trip5_duration: "يوم كامل",
    trip5_location: "جزيرة هولا هولا، الغردقة",
    trip6_full_title: "جزيرة البراديس - الغطس والألعاب المائية",
    trip6_description: "رحلة يوم ممتع إلى جزيرة البراديس، الغردقة! استمتع بالغطس في ٢ موقع، ساعتين على الجزيرة، ووقفة ألعاب مائية، وتشمل:",
    trip6_point1: "٢ وقفة غطس",
    trip6_point2: "ساعتين على الجزيرة",
    trip6_point3: "وقفة ألعاب مائية",
    trip6_duration: "يوم كامل",
    trip6_location: "جزيرة البراديس، الغردقة",
    trip7_full_title: "سفاري جبل وصحراء",
    trip7_description: "رحلة سفاري مثيرة في جبال وصحراء مرسى علم تشمل ركوب باجي، وقفة بدوية، وركوب خيل وجمال، وتشمل:",
    trip7_point1: "ركوب باجي في الصحراء",
    trip7_point2: "زيارة معسكر بدوي",
    trip7_point3: "ركوب خيل وجمال",
    trip7_duration: "يوم كامل",
    trip7_location: "صحراء مرسى علم"
  },
  pl: {
    home: "Strona główna",
    gallery: "Galeria",
    about: "O nas",
    explore_trips: "Poznaj nasze rodzaje wycieczek",
    hero_desc: "Niezapomniane przeżycia z pełną obsługą w cenie.",
    trip1_title: "Satayah - Pływanie z delfinami",
    trip1_desc: "Ciesz się pływaniem z delfinami w Morzu Czerwonym.",
    trip2_title: "Marsa Mubarak - Żółwie i Diugoń",
    trip2_desc: "Rejs, aby zobaczyć żółwie, diugonie i rafy koralowe.",
    trip3_title: "Wyspy Hamata - 3 miejsca do nurkowania",
    trip3_desc: "Nurkowanie w 3 miejscach i wizyta na wyspie Siyal.",
    inclusive_meal: "Obiad + bufet w cenie",
    drinks: "Napoje przez całą wycieczkę",
    transport: "Transport z i do hotelu",
    about_title: "O Sea Moon Tours",
    about_desc: "Sea Moon Tours to profesjonalna firma organizująca morskie wycieczki w Marsa Alam, Egipt. Oferujemy niezapomniane przygody w Morzu Czerwonym – pływanie z delfinami, snorkeling i wycieczki po rafach koralowych.",
    contact_title: "Skontaktuj się z nami",
    trip_title: "Satayah - Pływanie z delfinami",
    trip_description: "Niezapomniane doświadczenie pływania z delfinami w czystych wodach Satayah! Dołącz do nas na niesamowitą morską przygodę, która obejmuje rejs łodzią i czas z delfinami, z profesjonalnymi przewodnikami i pełnym wyposażeniem bezpieczeństwa.",
    price: "Cena",
    duration: "Czas trwania",
    trip_duration: "Cały dzień",
    location: "Lokalizacja",
    trip_location: "Rafa Satayah, Marsa Alam",
    book_now: "Pokaż szczegóły",
    trip2_full_title: "Marsa Mubarak - Pływanie z diugoniami i żółwiami",
    trip2_description: "Wyjątkowa morska wycieczka w Marsa Mubarak! Nurkowanie w dwóch pięknych miejscach, aby zobaczyć diugonie i żółwie morskie w turkusowych wodach. W cenie:",
    trip2_point1: "🏖️ Dwa miejsca do pływania i nurkowania",
    trip2_point2: "🐢 Zobacz diugonie i żółwie w ich naturalnym środowisku",
    trip2_point3: "🍽️ Pyszny lunch na pokładzie",
    trip2_point4: "🥤 Gorące i zimne napoje przez cały dzień",
    trip2_point5: "🚐 Transport z i do hotelu w cenie",
    trip2_location: "Marsa Mubarak, Marsa Alam",
    trip2_duration: "Cały dzień",
    trip3_title: "Wyspy Hamata - Snurkowanie w 3 miejscach i wyspa Siyal",
    trip3_description: "Ciesz się całodniową przygodą ze snurkowaniem w 3 pięknych miejscach rafowych i wizytą na wyspie Siyal.",
    trip3_point1: "Snurkowanie w 3 różnych lokalizacjach",
    trip3_point2: "Wizyta na dziewiczej wyspie Siyal",
    trip3_point3: "Smaczny lunch w formie bufetu na pokładzie",
    trip3_point4: "Gorące i zimne napoje przez cały dzień",
    trip3_point5: "Transfer z/do hotelu w cenie",
    trip3_duration: "Cały dzień",
    trip3_location: "Hamata",
    trip4_full_title: "Orange Bay - Nurkowanie i zabawy wodne",
    trip4_description: "Zabawny dzień na Orange Bay w Hurghadzie! Ciesz się nurkowaniem w 2 miejscach i 2 godzinami zabaw wodnych na wyspie. W cenie:",
    trip4_point1: "Dwa miejsca do nurkowania",
    trip4_point2: "Dwie godziny zabaw wodnych na wyspie",
    trip4_duration: "Cały dzień",
    trip4_location: "Orange Bay, Hurghada",
    trip5_full_title: "Hula Hula Island - Nurkowanie i zabawy wodne",
    trip5_description: "Zabawny dzień na Hula Hula Island w Hurghadzie! Ciesz się nurkowaniem w 2 miejscach i 2 godzinami zabaw wodnych na wyspie. W cenie:",
    trip5_point1: "Dwa miejsca do nurkowania",
    trip5_point2: "Dwie godziny zabaw wodnych na wyspie",
    trip5_duration: "Cały dzień",
    trip5_location: "Hula Hula Island, Hurghada",
    trip6_full_title: "Paradise Island - Nurkowanie i zabawy wodne",
    trip6_description: "Zabawny dzień na Paradise Island w Hurghadzie! Ciesz się nurkowaniem w 2 miejscach, 2 godzinami na wyspie i zabawami wodnymi. W cenie:",
    trip6_point1: "Dwa miejsca do nurkowania",
    trip6_point2: "Dwie godziny na wyspie",
    trip6_point3: "Zabawy wodne",
    trip6_duration: "Cały dzień",
    trip6_location: "Paradise Island, Hurghada",
    trip7_full_title: "Safari Górskie i Pustynne",
    trip7_description: "Ekscytująca safari w górach i pustyni Marsa Alam z jazdą na buggy, wizytą w obozie Beduinów i jazdą na koniach oraz wielbłądach. W cenie:",
    trip7_point1: "Jazda na buggy przez pustynię",
    trip7_point2: "Wizyta w obozie Beduinów",
    trip7_point3: "Jazda na koniach i wielbłądach",
    trip7_duration: "Cały dzień",
    trip7_location: "Pustynia Marsa Alam"
  },
  cz: {
    home: "Domů",
    gallery: "Galerie",
    about: "O nás",
    explore_trips: "Prozkoumejte naše typy výletů",
    hero_desc: "Nezapomenutelné zážitky se všemi službami v ceně.",
    trip1_title: "Satayah - Plavání s delfíny",
    trip1_desc: "Užijte si plavání s delfíny v Rudém moři.",
    trip2_title: "Marsa Mubarak - Želvy a Dugong",
    trip2_desc: "Výlet za želvami, dugongy a korálovými útesy.",
    trip3_title: "Hamata ostrovy - 3 šnorchlovací místa",
    trip3_desc: "Šnorchlování na 3 místech a návštěva ostrova Siyal.",
    inclusive_meal: "Zahrnuje oběd + otevřený bufet",
    drinks: "Nápoje po celou dobu výletu",
    transport: "Doprava z/do hotelu",
    about_title: "O společnosti Sea Moon Tours",
    about_desc: "Sea Moon Tours je profesionální společnost pořádající mořské výlety v Marsa Alam, Egypt. Nabízíme nezapomenutelná dobrodružství – plavání s delfíny, šnorchlování a prohlídky korálových útesů.",
    contact_title: "Kontaktujte nás",
    trip_title: "Satayah - Plavání s delfíny",
    trip_description: "Nezapomenutelný zážitek z plavání s delfíny v křišťálově čistých vodách Satayah! Připojte se k nám na úžasné mořské dobrodružství, které zahrnuje výlet lodí a čas s delfíny, s profesionálními průvodci a kompletním bezpečnostním vybavením.",
    price: "Cena",
    duration: "Doba trvání",
    trip_duration: "Celý den",
    location: "Místo",
    trip_location: "Satayah Reef, Marsa Alam",
    book_now: "Zobrazit podrobnosti",
    trip2_full_title: "Marsa Mubarak - Plavání s dugongy a želvami",
    trip2_description: "Speciální mořský výlet v Marsa Mubarak! Šnorchlování na dvou nádherných místech k pozorování dugongů a mořských želv v tyrkysové vodě. Zahrnuje:",
    trip2_point1: "🏖️ Dvě místa na šnorchlování a plavání",
    trip2_point2: "🐢 Pozorování dugongů a želv v jejich přirozeném prostředí",
    trip2_point3: "🍽️ Lahodný oběd na palubě",
    trip2_point4: "🥤 Teplé a studené nápoje po celý den",
    trip2_point5: "🚐 Doprava z/do hotelu v ceně",
    trip2_location: "Marsa Mubarak, Marsa Alam",
    trip2_duration: "Celý den",
    trip3_title: "Hamata ostrovy – šnorchlování na 3 místech a návštěva ostrova Siyal",
    trip3_description: "Užijte si celodenní dobrodružství se šnorchlováním na 3 krásných místech a návštěvu ostrova Siyal.",
    trip3_point1: "Šnorchlování na 3 různých místech",
    trip3_point2: "Návštěva nedotčeného ostrova Siyal",
    trip3_point3: "Lahodný oběd formou bufetu na palubě",
    trip3_point4: "Teplé a studené nápoje po celý den",
    trip3_point5: "Přeprava z/do hotelu v ceně",
    trip3_duration: "Celý den",
    trip3_location: "Hamata",
    trip4_full_title: "Orange Bay - Šnorchlování a vodní aktivity",
    trip4_description: "Zábavný den na Orange Bay v Hurghadě! Užijte si šnorchlování na 2 místech a 2 hodiny vodních aktivit na ostrově. Zahrnuje:",
    trip4_point1: "Dva místa na šnorchlování",
    trip4_point2: "Dvě hodiny vodních aktivit na ostrově",
    trip4_duration: "Celý den",
    trip4_location: "Orange Bay, Hurghada",
    trip5_full_title: "Hula Hula Island - Šnorchlování a vodní aktivity",
    trip5_description: "Zábavný den na Hula Hula Island v Hurghadě! Užijte si šnorchlování na 2 místech a 2 hodiny vodních aktivit na ostrově. Zahrnuje:",
    trip5_point1: "Dva místa na šnorchlování",
    trip5_point2: "Dvě hodiny vodních aktivit na ostrově",
    trip5_duration: "Celý den",
    trip5_location: "Hula Hula Island, Hurghada",
    trip6_full_title: "Paradise Island - Šnorchlování a vodní aktivity",
    trip6_description: "Zábavný den na Paradise Island v Hurghadě! Užijte si šnorchlování na 2 místech, 2 hodiny na ostrově a vodní aktivity. Zahrnuje:",
    trip6_point1: "Dva místa na šnorchlování",
    trip6_point2: "Dvě hodiny na ostrově",
    trip6_point3: "Vodní aktivity",
    trip6_duration: "Celý den",
    trip6_location: "Paradise Island, Hurghada",
    trip7_full_title: "Safar v Horách a Pustině",
    trip7_description: "Výlet safari v horách a pustině Marsa Alam s jízdou na buggy, návštěvou beduínského tábora a jízdou na koních a velbloudech. Zahrnuje:",
    trip7_point1: "Jízda na buggy přes poušť",
    trip7_point2: "Návštěva beduínského tábora",
    trip7_point3: "Jízda na koních a velbloudech",
    trip7_duration: "Celý den",
    trip7_location: "Pustina Marsa Alam"
  }
};

const switcher = document.getElementById("languageSwitcher");
const hamburger = document.querySelector('.hamburger');
const navLinks = document.querySelector('.nav-links');

switcher.addEventListener("change", changeLanguage);
hamburger.addEventListener('click', () => {
  navLinks.classList.toggle('active');
});

document.addEventListener("DOMContentLoaded", () => {
  changeLanguage(); // load default language
});

function changeLanguage() {
  const selectedLang = switcher.value;
  const elements = document.querySelectorAll("[data-i18n]");
  elements.forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (translations[selectedLang][key]) {
      el.textContent = translations[selectedLang][key];
    }
  });

  // Change direction for Arabic
  document.body.dir = selectedLang === "ar" ? "rtl" : "ltr";
}